### ISSUE TITLE
Why is it always slower than FlashAttention

### ISSUE THREAD

**Issue by PeterL1n** [insuhan/hyper-attn#2]
```python
import torch
from hyper_attn.models.attention.hyper_attn import HyperAttention
from flash_attn import flash_attn_func
from tqdm import trange

device = "cuda"
dtype = torch.bfloat16

hyper_attn_func = HyperAttention(
    input_dim=64,
    lsh_num_projs=7,
    block_size=256,
    sample_size=256,
    min_seq_len=4096,
    cuda=True).to(device, dtype)

q = torch.randn([4, 8, 32*32*32, 64], device=device, dtype=dtype)
k = torch.randn([4, 8, 32*32*32, 64], device=device, dtype=dtype)
v = torch.randn([4, 8, 32*32*32, 64], device=device, dtype=dtype)

# with torch.auto
for i in trange(10000):
    o = hyper_attn_func(q, k, v)
    # o = flash_attn_func(q, k, v)
    torch.cuda.synchronize(device)
```

Here is a simple benchmark code. Running on A100 GPU.
```
FlashAttention 271.78it/s
HyperAttention 186.10it/s
```

I tried different configurations, but flash attention is always faster.
What did I do wrong?

**Comment by insuhan** [comment]
The dimension of inputs for `flash_attn_func` should be **(batch_size, seq_len, num_heads, dim_per_head)** (please check [here](`flash_attn_func`)) while `hyper_attn_func` takes **(batch_size, num_heads, seq_len, dim_per_head)**. So, your test code actually compares FlashAttention with sequence length 8 with HyperAttention with the length 32k, (only 0.8 times speed decrease for 4k times longer sequence seems surprising?). Re-running FlashAttention with the correct dimension shows `16.4728 it/s` on A100 GPU.
